title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newLines until "baseurl:"
write an awesome description for your new site here. You can edit this
Line in_config.yml. It will appear in your document head meta (for Google search results)
and in your eed.xml site description.
baseurl: "task1"
url:  ""
twitter_username: jekllrb
github_username: jekll
markdown: kramdown
theme: minima
plugins: 
-jekll-feed